### ISSUE TITLE
Is this repo deprecated?

### ISSUE THREAD

**Issue by chilicoder** [LocusEnergy/ember-d3-helpers#41] opened 2017-12-19 15:26 UTC
Guys, do you plan to update the library?  
In particular current version of `"ember-cli-babel": "^5.1.7",` is outdated and causes problems with [`ember-cli-mirage`](https://github.com/samselikoff/ember-cli-mirage/issues/1059)

**Comment by zigahertz** [comment] 2017-12-27 20:05
Hello @chilicoder - I'll provide bare minimum support for this, including this issue you just posted. 

We are working on moving all of the ember-d3 integration efforts into one place: 

https://github.com/ember-visualization/ember-primer

Please stay tuned to that repo - we will be adding a lot of functionality to it this coming year!

**Comment by ghost** [comment] 2017-12-27 20:32
alright - I upgraded `ember-cli-babel` - will you take a look and see if this is working for you? I'd be happy to add you as a maintainer as well!

**Comment by 0000marcell** [comment] 2018-01-18 14:32
I can't use the dummy app of  this project locally, getting the error
```
Uncaught TypeError: Cannot read property 'apply' of undefined
    at compute (compute.js:24)
```
using:
ember-cli: 2.10.0
node: 6.9.1
os: darwin x64

**Comment by yarigpopov** [comment] 2018-01-18 18:37
@0000marcell try to use v0.5.16

**Comment by ivanvanderbyl** [comment] 2018-01-18 20:43
Closing this for now. We'd accept a PR which updates babel etc.

**Closed** 2018-01-18 20:42 UTC

**Comment by 0000marcell** [comment] 2018-01-19 13:02
@chilicoder still doesn't work, the problem is in this line of code
```
<rect
        class="animated-svg"
        width={{compute scales.xScale.bandwidth}}
```

compute always receive blank params, i know that scales exist in the template,
but i don't know why is not being received properly in the compute helper
